--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/elpepe44/.config/i3/walls/shinobu-a-contra-luz-de-la-luna_3840x2160_xtrafondos.com.jpg"

-- Special
background="#06060E"
foreground="#e3e8f5"
cursor="#e3e8f5"

-- Colors
color0="#06060E"
color1="#0956DF"
color2="#936DB3"
color3="#628AC2"
color4="#A3A2DA"
color5="#B5ADE2"
color6="#D2D3FB"
color7="#e3e8f5"
color8="#9ea2ab"
color9="#0956DF"
color10="#936DB3"
color11="#628AC2"
color12="#A3A2DA"
color13="#B5ADE2"
color14="#D2D3FB"
color15="#e3e8f5"
